### ISSUE TITLE
hello, really good and helpful extension... there is any chance to upgrade with more tickets, there are many many coin missing. Thanks again

### ISSUE THREAD

**Issue by MrKlesk** [walkjivefly/LOC-Extension#11]
Thank you for taking the time to report an issue. To help me help you please specify

**Comment by walkjivefly** [comment]
The extension is built on a snapshot of ccxt, which doubtless now handles more exchanges and coins than the embedded version. I don't have the time or inclination to refresh the snapshot but anyone is free to do so if they wish. There have been a couple of forks of the repo recently so perhaps an updated version will be forthcoming, soon (TM)

**Comment by walkjivefly** [comment]
Closed
